# Generated by Django 5.0.6 on 2024-06-11 12:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0006_userquizresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquizresult',
            name='completed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
