# Generated by Django 5.0.6 on 2024-06-12 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0009_remove_question_correct_option_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Option',
            new_name='Answer',
        ),
        migrations.RenameField(
            model_name='useranswer',
            old_name='selected_options',
            new_name='selected_answers',
        ),
    ]
