# Generated by Django 5.0.6 on 2024-06-12 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0013_quizaccess'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quizaccess',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='quizaccess',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quizzes.department'),
        ),
        migrations.AlterUniqueTogether(
            name='quizaccess',
            unique_together={('quiz', 'organization', 'department')},
        ),
    ]
