# Generated by Django 5.0.6 on 2024-06-14 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0017_userexamaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='duration',
            field=models.IntegerField(default=10),
        ),
    ]
