# Generated by Django 5.0.6 on 2024-06-14 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0018_quiz_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='userexamaccess',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userexamaccess',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
